output:
  year: 2020
  month:      # 何も書かないと1年分生成
font: ./GN-KillGothic-U-KanaNA.ttf
size: 30.0
image:
  width: 1500
  height: 1000
color:
  weekday:  [0x51, 0x51, 0x51]
  saturday: [0x62, 0x88, 0xe3]
  sunday:   [0xd9, 0x6b, 0x6b]
XPos: # 横方向の描画開始位置。f(x) = 150x - 7
  - 0
  - 143
  - 286
  - 429
  - 572
  - 715
  - 858
YPos: # 縦方向の描画開始位置。f(y) = 145y + 90 + 2
  - 90
  - 235
  - 382
  - 527
  - 672
  - 817

