output:
  year: 2020
  month: 1
font: ./GN-KillGothic-U-KanaNA.ttf
size: 60.0
image:
  width: 1500
  height: 1000
XPos:
  - 0
  - 143
  - 286
  - 429
  - 572
  - 715
  - 858
YPos:
  - 90
  - 235
  - 382
  - 527
  - 672
  - 817

